apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-view-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-view-pods
subjects:
  - kind: ServiceAccount
    name: ansible-builder-shipwright
